---
- name: Install RLY from source
  become: false
  block:
    - name: Clone node repo
      git:
        repo: '{{ rly_repo }}'
        dest: '{{ user_dir }}/rly'
        version: '{{ rly_version }}'
        update: yes
        force: yes
        recursive: no

    - name: Install node
      command: '{{ item }}'
      args:
        chdir: '{{ user_dir }}/rly'
      with_items:
        - 'make install'
      environment:
        PATH: '{{ path }}'
        GOPATH: '{{ user_dir }}/go'
